Parameters:
  LambdaExecutionRoleArn:
    Type: String

Resources:
  BadgeRedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      Runtime: nodejs22.x
      MemorySize: 128
      Timeout: 5
      Role: !Ref LambdaExecutionRoleArn
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
