AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  LambdaExecutionRoleArn:
    Type: String
    Description: "ARN of the IAM Role for Lambda execution"

Resources:
  BadgeRedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      Runtime: nodejs22.x
      MemorySize: 128
      Timeout: 5
      Role: !Ref LambdaExecutionRoleArn
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
