AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda redirect function with custom domain (SAM fully managed)

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs22.x
    MemorySize: 128

Parameters:
  CertificateArn:
    Type: String
    Description: "ACM certificate ARN for custom domain"

Resources:
  RedirectHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      Domain:
        DomainName: badge.pelagornis.com
        CertificateArn: !Ref CertificateArn

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: dist
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref RedirectHttpApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway custom domain URL"
    Value: !Sub "https://${RedirectHttpApi.Domain.DomainName}/"
