name: Deploy Lambda via SAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 3. Node.js 설치 (TypeScript 빌드를 위해 필요)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 4. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 5. TypeScript 빌드
      - name: Build TypeScript
        run: npm run build

      # 6. SAM CLI 설치
      - name: Install SAM CLI
        run: pip install aws-sam-cli

      # 7. Lambda 빌드
      - name: Build Lambda with SAM
        run: sam build

      # 8. Lambda 배포
      - name: Deploy Lambda
        env:
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          sam deploy \
            --stack-name badge \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --resolve-s3 \
            --parameter-overrides CertificateArn=${{ secrets.CERTIFICATE_ARN }}
