name: Deploy Lambda with OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Install dependencies
        run: npm ci

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        run: |
          sam deploy \
            --stack-name badge-stack \
            --s3-bucket pelagornis-badge-redirect-stack \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --region ap-northeast-2 \
            --parameter-overrides LambdaExecutionRoleArn=${{ secrets.AWS_ROLE_ARN }}
