name: Deploy Lambda with OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write # OIDC 토큰 요청 권한
  contents: read # 리포지토리 내용 읽기 권한

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Install dependencies
        run: npm ci

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        run: |
          sam deploy \
            --stack-name ${{ secrets.AWS_S3_STACK }} \
            --s3-bucket ${{ secrets.AWS_S3_BUCKET }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --region ap-northeast-2
            --parameter-overrides LambdaExecutionRoleArn=${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}
