name: Deploy Lambda with OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write # OIDC 토큰 요청 권한
  contents: read # 코드 체크아웃 권한

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/badge
          aws-region: ap-northeast-2

      - name: Install dependencies
        run: npm ci

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        run: sam deploy \
          --stack-name badge-redirect-stack \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --region ap-northeast-2
