name: Deploy badges.conf to EC2

on:
  push:
    paths:
      - "nginx/badges.conf"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy badges.conf to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "nginx/badges.conf"
          target: "/tmp/"

      - name: SSH to EC2 and move config, reload nginx
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mv /tmp/badges.conf /etc/nginx/conf.d/badges.conf
            sudo nginx -t && sudo systemctl reload nginx
